services:
  app:
    container_name: Demo-App
    image: demo-app
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
    restart: always
    networks:
      - network1


networks:
  network1:
    name: full-stack-docker-tazama_default
    external: true
      