export const ACTIONS = {
  CREATE_ENTITY_LOADING: "CREATE_ENTITY_LOADING",
  CREATE_ENTITY_SUCCESS: "CREATE_ENTITY_SUCCESS",
  CREATE_ENTITY_FAIL: "CREATE_ENTITY_FAIL",

  UPDATE_ENTITY_LOADING: "UPDATE_ENTITY_LOADING",
  UPDATE_ENTITY_SUCCESS: "UPDATE_ENTITY_SUCCESS",
  UPDATE_ENTITY_FAIL: "UPDATE_ENTITY_FAIL",

  CREATE_ENTITY_ACCOUNT_LOADING: "CREATE_ENTITY_ACCOUNT_LOADING",
  CREATE_ENTITY_ACCOUNT_SUCCESS: "CREATE_ENTITY_ACCOUNT_SUCCESS",
  CREATE_ENTITY_ACCOUNT_FAIL: "CREATE_ENTITY_ACCOUNT_FAIL",

  CREATE_CREDITOR_ENTITY_LOADING: "CREATE_CREDITOR_ENTITY_LOADING",
  CREATE_CREDITOR_ENTITY_SUCCESS: "CREATE_CREDITOR_ENTITY_SUCCESS",
  CREATE_CREDITOR_ENTITY_FAIL: "CREATE_CREDITOR_ENTITY_FAIL",

  UPDATE_CREDITOR_ENTITY_LOADING: "UPDATE_CREDITOR_ENTITY_LOADING",
  UPDATE_CREDITOR_ENTITY_SUCCESS: "UPDATE_CREDITOR_ENTITY_SUCCESS",
  UPDATE_CREDITOR_ENTITY_FAIL: "UPDATE_CREDITOR_ENTITY_FAIL",

  CREATE_CREDITOR_ENTITY_ACCOUNT_LOADING: "CREATE_CREDITOR_ENTITY_ACCOUNT_LOADING",
  CREATE_CREDITOR_ENTITY_ACCOUNT_SUCCESS: "CREATE_CREDITOR_ENTITY_ACCOUNT_SUCCESS",
  CREATE_CREDITOR_ENTITY_ACCOUNT_FAIL: "CREATE_CREDITOR_ENTITY_ACCOUNT_FAIL",

  SET_DEBTOR_PACS008_LOADING: "SET_DEBTOR_PACS008_LOADING",
  SET_DEBTOR_PACS008_SUCCESS: "SET_DEBTOR_PACS008_SUCCESS",
  SET_DEBTOR_PACS008_FAIL: "SET_DEBTOR_PACS008_FAIL",

  SET_CREDITOR_PACS008_LOADING: "SET_CREDITOR_PACS008_LOADING",
  SET_CREDITOR_PACS008_SUCCESS: "SET_CREDITOR_PACS008_SUCCESS",
  SET_CREDITOR_PACS008_FAIL: "SET_CREDITOR_PACS008_FAIL",
}
