export const ACTIONS = {
  CREATE_ENTITY_LOADING: "CREATE_ENTITY_LOADING",
  CREATE_ENTITY_SUCCESS: "CREATE_ENTITY_SUCCESS",
  CREATE_ENTITY_FAIL: "CREATE_ENTITY_FAIL",

  UPDATE_ENTITY_LOADING: "UPDATE_ENTITY_LOADING",
  UPDATE_ENTITY_SUCCESS: "UPDATE_ENTITY_SUCCESS",
  UPDATE_ENTITY_FAIL: "UPDATE_ENTITY_FAIL",

  CREATE_ENTITY_ACCOUNT_LOADING: "CREATE_ENTITY_ACCOUNT_LOADING",
  CREATE_ENTITY_ACCOUNT_SUCCESS: "CREATE_ENTITY_ACCOUNT_SUCCESS",
  CREATE_ENTITY_ACCOUNT_FAIL: "CREATE_ENTITY_ACCOUNT_FAIL",

  CREATE_CREDITOR_ENTITY_LOADING: "CREATE_CREDITOR_ENTITY_LOADING",
  CREATE_CREDITOR_ENTITY_SUCCESS: "CREATE_CREDITOR_ENTITY_SUCCESS",
  CREATE_CREDITOR_ENTITY_FAIL: "CREATE_CREDITOR_ENTITY_FAIL",

  UPDATE_CREDITOR_ENTITY_LOADING: "UPDATE_CREDITOR_ENTITY_LOADING",
  UPDATE_CREDITOR_ENTITY_SUCCESS: "UPDATE_CREDITOR_ENTITY_SUCCESS",
  UPDATE_CREDITOR_ENTITY_FAIL: "UPDATE_CREDITOR_ENTITY_FAIL",

  CREATE_CREDITOR_ENTITY_ACCOUNT_LOADING: "CREATE_CREDITOR_ENTITY_ACCOUNT_LOADING",
  CREATE_CREDITOR_ENTITY_ACCOUNT_SUCCESS: "CREATE_CREDITOR_ENTITY_ACCOUNT_SUCCESS",
  CREATE_CREDITOR_ENTITY_ACCOUNT_FAIL: "CREATE_CREDITOR_ENTITY_ACCOUNT_FAIL",

  UPDATE_ACCOUNTS_LOADING: "UPDATE_ACCOUNTS_LOADING",
  UPDATE_ACCOUNTS_SUCCESS: "UPDATE_ACCOUNTS_SUCCESS",
  UPDATE_ACCOUNTS_FAIL: "UPDATE_ACCOUNTS_FAIL",

  SET_DEBTOR_PACS008_LOADING: "SET_DEBTOR_PACS008_LOADING",
  SET_DEBTOR_PACS008_SUCCESS: "SET_DEBTOR_PACS008_SUCCESS",
  SET_DEBTOR_PACS008_FAIL: "SET_DEBTOR_PACS008_FAIL",

  SET_DEBTOR_ACCOUNT_PACS008_LOADING: "SET_DEBTOR_ACCOUNT_PACS008_LOADING",
  SET_DEBTOR_ACCOUNT_PACS008_SUCCESS: "SET_DEBTOR_ACCOUNT_PACS008_SUCCESS",
  SET_DEBTOR_ACCOUNT_PACS008_FAIL: "SET_DEBTOR_ACCOUNT_PACS008_FAIL",

  SET_CREDITOR_PACS008_LOADING: "SET_CREDITOR_PACS008_LOADING",
  SET_CREDITOR_PACS008_SUCCESS: "SET_CREDITOR_PACS008_SUCCESS",
  SET_CREDITOR_PACS008_FAIL: "SET_CREDITOR_PACS008_FAIL",

  SET_CREDITOR_ACCOUNT_PACS008_LOADING: "SET_CREDITOR_ACCOUNT_PACS008_LOADING",
  SET_CREDITOR_ACCOUNT_PACS008_SUCCESS: "SET_CREDITOR_ACCOUNT_PACS008_SUCCESS",
  SET_CREDITOR_ACCOUNT_PACS008_FAIL: "SET_CREDITOR_ACCOUNT_PACS008_FAIL",

  GENERATE_TRANSACTION_PACS008_LOADING: "GENERATE_TRANSACTION_PACS008_LOADING",
  GENERATE_TRANSACTION_PACS008_SUCCESS: "GENERATE_TRANSACTION_PACS008_SUCCESS",
  GENERATE_TRANSACTION_PACS008_FAIL: "GENERATE_TRANSACTION_PACS008_FAIL",

  SELECT_DEBTOR_ENTITY: "SELECT_DEBTOR_ENTITY",
  SELECT_CREDITOR_ENTITY: "SELECT_CREDITOR_ENTITY",

  POST_PACS008_LOADING: "POST_PACS008_LOADING",
  POST_PACS008_SUCCESS: "POST_PACS008_SUCCESS",
  POST_PACS008_FAIL: "POST_PACS008_FAIL",

  GENERATE_PACS002_LOADING: "GENERATE_PACS002_LOADING",
  GENERATE_PACS002_SUCCESS: "GENERATE_PACS002_SUCCESS",
  GENERATE_PACS002_FAIL: "GENERATE_PACS002_FAIL",

  POST_PACS002_LOADING: "POST_PACS002_LOADING",
  POST_PACS002_SUCCESS: "POST_PACS002_SUCCESS",
  POST_PACS002_FAIL: "POST_PACS002_FAIL",

  SET_RULE_LIGHTS_LOADING: "SET_RULE_LIGHTS_LOADING",
  SET_RULE_LIGHTS_SUCCESS: "SET_RULE_LIGHTS_SUCCESS",
  SET_RULE_LIGHTS_FAIL: "SET_RULE_LIGHTS_FAIL",
}
