export const ACTIONS = {
  CREATE_ENTITY_LOADING: "CREATE_ENTITY_LOADING",
  CREATE_ENTITY_SUCCESS: "CREATE_ENTITY_SUCCESS",
  CREATE_ENTITY_FAIL: "CREATE_ENTITY_FAIL",

  UPDATE_ENTITY_LOADING: "UPDATE_ENTITY_LOADING",
  UPDATE_ENTITY_SUCCESS: "UPDATE_ENTITY_SUCCESS",
  UPDATE_ENTITY_FAIL: "UPDATE_ENTITY_FAIL",

  CREATE_ENTITY_ACCOUNT_LOADING: "CREATE_ENTITY_ACCOUNT_LOADING",
  CREATE_ENTITY_ACCOUNT_SUCCESS: "CREATE_ENTITY_ACCOUNT_SUCCESS",
  CREATE_ENTITY_ACCOUNT_FAIL: "CREATE_ENTITY_ACCOUNT_FAIL",

  CREATE_CREDITOR_ENTITY_LOADING: "CREATE_CREDITOR_ENTITY_LOADING",
  CREATE_CREDITOR_ENTITY_SUCCESS: "CREATE_CREDITOR_ENTITY_SUCCESS",
  CREATE_CREDITOR_ENTITY_FAIL: "CREATE_CREDITOR_ENTITY_FAIL",

  UPDATE_CREDITOR_ENTITY_LOADING: "UPDATE_CREDITOR_ENTITY_LOADING",
  UPDATE_CREDITOR_ENTITY_SUCCESS: "UPDATE_CREDITOR_ENTITY_SUCCESS",
  UPDATE_CREDITOR_ENTITY_FAIL: "UPDATE_CREDITOR_ENTITY_FAIL",

  CREATE_CREDITOR_ENTITY_ACCOUNT_LOADING: "CREATE_CREDITOR_ENTITY_ACCOUNT_LOADING",
  CREATE_CREDITOR_ENTITY_ACCOUNT_SUCCESS: "CREATE_CREDITOR_ENTITY_ACCOUNT_SUCCESS",
  CREATE_CREDITOR_ENTITY_ACCOUNT_FAIL: "CREATE_CREDITOR_ENTITY_ACCOUNT_FAIL",
}
