export const ACTIONS = {
  CREATE_RULES_LOADING: "CREATE_RULES_LOADING",
  CREATE_RULES_SUCCESS: "CREATE_RULES_SUCCESS",
  CREATE_RULES_FAIL: "CREATE_RULES_FAIL",

  UPDATE_RULES_LOADING: "UPDATE_RULES_LOADING",
  UPDATE_RULES_SUCCESS: "UPDATE_RULES_SUCCESS",
  UPDATE_RULES_FAIL: "UPDATE_RULES_FAIL",

  UPDATE_TADPROC_LOADING: "UPDATE_TADPROC_LOADING",
  UPDATE_TADPROC_SUCCESS: "UPDATE_TADPROC_SUCCESS",
  UPDATE_TADPROC_FAIL: "UPDATE_TADPROC_FAIL",

  RESET_ALL_LIGHTS: "RESET_ALL_LIGHTS",
}
